---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: bento/ubuntu-14.04
    driver_config:
      customize:
        memory: 768
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[sftp::default]
    attributes:
